coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("products.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import MyOrderView, CreateOrderProduct, DeleteOrderProduct


urlpatterns = [
    path("my_order/", MyOrderView.as_view(), name="MyOrder"),
    path("add_product_order/", CreateOrderProduct.as_view(), name="CreateOrderProduct"),
    path(
        "delete_product_order/<int:pk>/",
        DeleteOrderProduct.as_view(),
        name="DeleteOrderProduct",
    ),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import ProductListView, ProductFormView, ProductListAPI

urlpatterns = [
    path("", ProductListView.as_view(), name="all_products"),
    path("add_product/", ProductFormView.as_view(), name="add_product"),
    path("api/", ProductListAPI.as_view(), name="all_produts_api"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} by {self.user}"


class Order_product(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.order} => {self.product}"

products/models.py
from django.db import models


class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name="nombre")
    description = models.TextField(max_length=300, verbose_name="descripcion")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="precio")
    available = models.BooleanField(default=True, verbose_name="disponible")
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="foto"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fechaCreación")

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django.forms import Form, ModelForm
from .models import Order_product


class Order_productForm(ModelForm):
    class Meta:
        model = Order_product
        fields = ["product"]

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label="Descripcion")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    available = forms.BooleanField(initial=True, label="Disponible", required=True)
    photo = forms.ImageField(label="Foto", required=False)

    def save(self):
        Product.objects.create(
            name=self.cleaned_data["name"],
            description=self.cleaned_data["description"],
            price=self.cleaned_data["price"],
            available=self.cleaned_data["available"],
            photo=self.cleaned_data["photo"],
        )

orders/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from .models import Order, Order_product
from .forms import Order_productForm


class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/order.html"
    context_object_name = "order"

    def get_object(self, queryset=None):
        return Order.objects.filter(is_active=True, user=self.request.user).first()


class CreateOrderProduct(LoginRequiredMixin, CreateView):
    model = Order_product
    # template_name = "orders/create_order.html"
    form_class = Order_productForm
    success_url = reverse_lazy("MyOrder")

    def form_valid(self, form):
        order, _ = Order.objects.get_or_create(is_active=True, user=self.request.user)

        form.instance.order = order
        form.instance.quantity = 1
        form.save()

        return super().form_valid(form)


class DeleteOrderProduct(LoginRequiredMixin, DeleteView):
    model = Order_product
    success_url = reverse_lazy("MyOrder")
    # template_name = 'orders/confirm_delete_product.html'

    def get_object(self, queryset=None):
        """
        Obtiene el producto a eliminar asegurando que pertenece al usuario autenticado.
        """
        return get_object_or_404(
            Order_product, pk=self.kwargs["pk"], order__user=self.request.user
        )

products/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.views import APIView
from rest_framework.response import Response

# MODELS
from products.models import Product
from products.forms import ProductForm
from .serializers import ProductSerializer


class ProductListView(TemplateView):
    template_name = "products/products.html"

    def get_context_data(self):
        products_list = Product.objects.all()
        return {"products_list": products_list}


class ProductFormView(LoginRequiredMixin, FormView):
    template_name = "products/add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy("all_products")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListAPI(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("login")

orders/templates/orders/order.html
{% extends "base.html" %}
{% block content %}
{% load static %}


<div class="relative flex min-h-screen flex-col justify-center overflow-hidden py-6 sm:py-12">
    <div class="absolute inset-0 bg-[url(/img/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
    <div class="relative bg-white px-6 pt-10 pb-8 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-10">
      <div class="mx-auto max-w-md">
        <div class="divide-y divide-gray-300/50">
          <div class="space-y-6 py-8 text-base leading-7 text-gray-600">
            <p class="text-lg font-bold text-gray-900">Detalle de la orden</p>
            <ul class="space-y-8">
              <li class="flex items-center">
                <p class="ml-4">
                 Usuario: 
                  <code class="text-sm font-bold text-gray-900">{{ order.user.username }}</code>
                </p>
              </li>
              <li class="flex items-center">
                <p class="ml-4">
                  Fecha de Orden: 
                  <code class="text-sm font-bold text-gray-900">{{ order.order_date | date }}</code>
                </p>
              </li>
              <li class="flex items-center">
                <ul class="list-disc">
                    <p class="ml-4">PRODUCTOS: </p>
                    {% for order_item in order.order_product_set.all %}
                        <li class="flex items-center justify-between">
                          <p class="ml-4">{{ order_item.product.name }} : {{ order_item.product.price }}</p>
                          <form action="{% url 'DeleteOrderProduct' order_item.id %}" method="post">
                              {% csrf_token %}
                              <input type="hidden" name="order_item.id" value="{{ order_item.id }}">
                              <button class="text-red-500 underline hover:text-red-700 font-medium">
                                  Eliminar
                              </button>
                          </form>
                      </li>
                    {% endfor %}
                </ul>
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

products/templates/products/add_product.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}
<main class="flex flex-col items-center justify-center px-8 py-8 sm:px-12 lg:col-span-7 lg:px-16 lg:py-12 xl:col-span-6">
    <h1 class="mt-6 text-2xl font-bold text-gray-900 sm:text-3xl md:text-4xl">PRODUCT FORM</h1>
    <div class="max-w-xl lg:max-w-3xl">
        <form action="{% url "add_product" %}" method="POST" class="mt-8 grid grid-cols-1 gap-6" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="Submit" class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow">Agregar</button>
        </form>
    </div>
</main>
<a href="{% url 'all_products' %}" class="button">Volver</a>
{% endblock content %}

products/templates/products/products.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    <h1 class="text-3xl font-bold text-center my-6">Product List</h1>
    
    <!-- Contenedor de las tarjetas -->
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 p-4">
        {% for product in products_list %}
        <a href="#" class="group relative block overflow-hidden">
            <button
              class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
            >
              <span class="sr-only">Wishlist</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
                />
              </svg>
            </button>
            {% if product.photo %}
                <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"/>
            {% else %}
                <img src="{% static "images/placeholder.png" %}" alt="PlaceHolder" class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"/>
            {% endif %}
            <div class="relative border border-gray-100 bg-white p-6">
              <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"> {{ product.created_at }} </span>
          
              <h3 class="mt-4 text-lg font-medium text-gray-900">{{ product.name }}</h3>
          
              <p class="mt-1.5 text-sm text-gray-700">${{ product.price }}</p>

              <form action="{% url "CreateOrderProduct" %}" class="mt-4" method="post">
                {% csrf_token %}
                <input type="hidden" name="product" value="{{product.id}}">
                <button class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105">
                  Agregar al pedido
                </button>
              </form>
            </div>
          </a>
        {% endfor %}
    </div>
    
    <!-- Botón de agregar producto -->
    <div class="text-center my-4">
        <a href="{% url 'add_product' %}" class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow">
            Agregar Producto
        </a>
    </div>
{% endblock content %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>COFFE SHOP</title>
    <style>

    </style>
</head>
<body class="bg-[#f8f5f0] text-gray-800 font-sans">
    <header class="bg-white shadow-md sticky top-0 z-10">
        <div class="mx-auto flex h-16 max-w-screen-xl items-center gap-8 px-4 sm:px-6 lg:px-8">
            <a class="block text-[#005f56] hover:text-[#007f6e] dark:text-teal-300" href="{% url 'all_products' %}">
                <span class="sr-only">Home</span>
                <svg class="h-10" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.68604 15H17.3146M6.51465 13H17.4861M7.74316 7H16.2571M7.74316 7C7.13829 7 6.8358 7 6.61279 7.12093C6.41686 7.22718 6.26205 7.3963 6.17292 7.60059C6.07151 7.83303 6.0973 8.13407 6.14893 8.73633L6.94921 18.073C7.0377 19.1053 7.08203 19.6225 7.31149 20.0132C7.51358 20.3572 7.81426 20.6327 8.17432 20.8047C8.58318 21 9.10126 21 10.1377 21H13.8628C14.8992 21 15.4174 21 15.8263 20.8047C16.1864 20.6327 16.4869 20.3572 16.689 20.0132C16.9185 19.6225 16.9628 19.1056 17.0513 18.073L17.8517 8.73471C17.9033 8.13312 17.929 7.8329 17.8276 7.60059C17.7385 7.3963 17.5838 7.22718 17.3878 7.12093C17.1648 7 16.862 7 16.2571 7M7.74316 7H6.7499C5.85031 7 5.40023 7 5.13867 6.81152C4.90778 6.64515 4.75884 6.38816 4.72894 6.10515C4.69504 5.78431 4.91871 5.3929 5.36568 4.6107L5.36621 4.60977C5.70039 4.02496 5.86748 3.73255 6.10197 3.51953C6.31161 3.32909 6.55925 3.18544 6.82861 3.09791C7.12991 3 7.46658 3 8.14014 3H15.8604C16.5339 3 16.8707 3 17.172 3.09791C17.4413 3.18544 17.6888 3.32909 17.8984 3.51953C18.1329 3.73255 18.3 4.02496 18.6342 4.60977C19.0813 5.39224 19.3053 5.78425 19.2714 6.10515C19.2415 6.38816 19.0925 6.64515 18.8616 6.81152C18.6001 7 18.1497 7 17.2501 7H16.2571" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="white"/>
                </svg>
            </a>
    
            <div class="flex flex-1 items-center justify-end md:justify-between">
                <nav aria-label="Global" class="hidden md:block">
                    <!-- Aquí puedes añadir más elementos de navegación -->
                    <a class="underline decoration-sky-500 mx-6">COFFE SHOP</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'MyOrder' %}" class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow">
                            Mi Pedido
                        </a>
                    {% endif %}
                </nav>
    
                <div class="flex items-center gap-4">
                    <div class="sm:flex sm:gap-4">
                        {% if user.is_authenticated %}
                        <span class="text-sm font-medium text-left">Hola, {{ user.username }}</span>
                        <form action="{% url 'logout' %}" method="POST">
                            {% csrf_token %}
                            <button class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow" type="submit">
                                Cerrar Sesíon
                            </button>
                        </form>
                        {% else %}
                            <a class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow" href="{% url 'login' %}">
                                Iniciar Sesíon
                            </a>
                            <a class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow" href="{% url 'register' %}">
                                Regístrate
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container mx-auto p-4">
        {% block content %}
        {% endblock content %}
    </div>
</body>


</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}
<section class="bg-white">
    <div class="lg:grid lg:min-h-screen lg:grid-cols-12">
      <aside class="relative block h-16 lg:order-last lg:col-span-5 lg:h-full xl:col-span-6">
        <img
          alt=""
          src="{% static "images/coffe_login.png" %}"
          class="absolute inset-0 h-full w-full object-cover"
        />
      </aside>
  
      <main
        class="flex items-center justify-center px-8 py-8 sm:px-12 lg:col-span-7 lg:px-16 lg:py-12 xl:col-span-6">
        <div class="max-w-xl lg:max-w-3xl">
          <h1 class="mt-6 text-2xl font-bold text-gray-900 sm:text-3xl md:text-4xl">
            Iniciar Sesion ☕
          </h1>
          <form action="" class="mt-8 grid grid-cols-1 gap-6" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="Submit" class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow">Ingresar</button>
          </form>
          <p class="mt-4 text-center text-sm text-gray-600">
            ¿No tienes cuenta? 
            <a href="{% url 'register' %}" class="font-medium text-yellow-500 hover:underline">
                Regístrate
            </a>
        </p>
        </div>
      </main>
    </div>
  </section>

{% comment %} 
<form action="" method="post">    
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="bg-yellow-400 hover:scale-105 font-bold py-1 px-4 rounded shadow">Ingresar</button>
</form> {% endcomment %}
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load static %}
{% block content %}
<main class="flex flex-col items-center justify-center px-8 py-8 sm:px-12 lg:col-span-7 lg:px-16 lg:py-12 xl:col-span-6">
    <h1 class="mt-6 text-2xl font-bold text-gray-900 sm:text-3xl md:text-4xl">PRODUCT FORM</h1>
    <div class="max-w-xl lg:max-w-3xl">
        <form action="{% url "register" %}" method="POST" class="mt-8 grid grid-cols-1 gap-6" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="Submit" class="bg-yellow-400 hover:scale-105 font-bold py-2 px-4 rounded shadow">Registrar</button>
        </form>
    </div>
</main>
{% endblock content %}
    